export { default as home } from './home.vue'
export { default as singout } from './singout.vue'
export { default as profilePicture } from './profilePicture.vue'
export { default as logo } from './logo.vue'
export { default as triangle } from './triangle.vue'
